---
title: "first_lake_report"
output:
  pdf_document: default
  html_document: default
date: "2025-03-18"
---

```{r setup, include=FALSE}
if (!require(dplyr)) {install.packages("dplyr")}
if (!require(tidyverse)) {install.packages("tidyverse")}

library(readr)
library(stringr)
```

## Downloading Folder with All Data\
```{r}
folder = "C:/Users/mvhfg/OneDrive - University of Missouri/North_Limnology/priv_lake_rep/Private_Lake_Reports/2024 Data"
files = list.files(
  path = folder,
  pattern = ".*csv$",
  ignore.case = F,
  full.names = T #provides path to folder
)

files2 <- list.files("2024 Data", pattern="*.csv")

library(readr)
library(stringr)

for(i in 1:length(files)) {
  file_name <- str_sub(string = files[i], start = 111)
  file_df <- read.csv(paste0(folder,"/",files2[i]),header = TRUE, sep=",")
  #file_df <- file_df[c(3:2714),2:3] #i only need the col 2&3 and keep rows 2:2714
  #cols <- names(file_df)[14] #getting the 14th column 
  #file_df[cols] <- lapply(file_df[cols], as.numeric) #making the cols column(s) numeric
  assign( x = file_name, value = file_df, envir = .GlobalEnv)
}
```


## Results

### Total Nitrogen & Total Phosphorus\
Total Phosphorus - Showing TP Data
```{r}
#all TP data
#we want to extract TP values for lake 14 - Tishomingo
# we are only looking at surface samples so the Depth has to be SURF
tp_14 <- SLAP_2024_TP.csv%>%
  filter(MULakeNumber == "014" & Depth == "SURF")
#for depth instead of looking for SURF, look for endDepth = 0
```

Averaging TP Data
```{r}
tp_14_avg <- tp_14 %>%
  group_by(Date)%>%
  summarise(Average_TP = mean(parameterValue)) #units in ug/L
```

Plot of TP
```{r}
tp_14_avg %>%
  ggplot( aes(x=Date, y=Average_TP)) +
  geom_hline(yintercept = 60.12, size = 2, color = "orchid4")+
  geom_line(aes(group=1), color = "gray76", size = 1.5)+
  geom_point(shape=21, color="black", fill="orchid4", size=8) +
    theme_bw()+
    theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())+
    xlab('Date')+
    ylab('TP Concentration (µg/L)')+
    labs(title = "Average Total Phosphorus Concentrations for Summer 2024")
```


Average TN Data
```{r}
tn_14 <- SLAP_2024_TN.csv%>%
  filter(MULakeNumber == "014" & endDepth == 0)

tn_14_avg <- tn_14 %>%
  group_by(Date)%>%
  summarise(Average_TN = mean(parameterValue)) #units in ug/L
```

Plot of TN
```{r}
tn_14_avg %>%
  ggplot( aes(x=Date, y=Average_TN)) +
  geom_hline(yintercept = 950.6, size = 2, color = "royalblue4")+
  geom_line(aes(group=1), color = "gray76", size = 1.5)+
  geom_point(shape=21, color="black", fill="royalblue4", size=8) +
    theme_bw()+
    theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())+
    xlab('Date')+
    ylab('TN Concentration (µg/L)')+
    labs(title = "Average Total Nitrogen Concentrations for Summer 2024")

#save in 600 by 400 png
```

### Toxins
```{r}
ANAtox <- SLAP_2024_ANA_tox.csv[,1:19] #keeps the first 19 columns
CLYtox <- SLAP_2024_CLY_tox.csv[,1:19]
MICtox <- SLAP_2024_MIC_tox.csv[,1:19]
SAXtox <- SLAP_2024_SAX_tox.csv[,1:19]

ANAtox_14 <- ANAtox%>%
  filter(MULakeNumber == "014")

CLYtox_14 <- CLYtox%>%
  filter(MULakeNumber == "014")

MICtox_14 <- MICtox%>%
  filter(MULakeNumber == "014")

SAXtox_14 <- SAXtox%>%
  filter(MULakeNumber == "014")

ALLtox_14 <- bind_rows(ANAtox_14, CLYtox_14, MICtox_14, SAXtox_14)  #units in ug/L
```

Full df of Toxins
```{r}
tox_avg_14 <- ALLtox_14 %>%
  group_by(Date, parameterType)%>%
  summarise(avg_tox = mean(parameterValue)) #units in ug/L

if (!require(ggplot2)) {install.packages("ggplot2")}


ggplot(tox_avg_14, aes(x=Date, y=avg_tox, group=parameterType)) +
  geom_line(size =0.75, aes(color =parameterType)) +
  geom_point(aes(shape=parameterType, color=parameterType, size=parameterType))+
  scale_shape_manual(values=c(15, 16, 17, 18))+
  scale_color_manual(values=c('brown4','orange', 'palegreen3', 'steelblue'))+
  scale_size_manual(values=c(8,8,5,6))+
  theme(legend.position="right")+
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())+
  xlab('Date')+
  ylab('Average Tox Concentration (µg/L)')+
  labs(title = "Cyanotoxin Concentrations for Summer 2024") 
#best one so far
```

### Secchi & CHL A

Secchi Depth Averages
```{r}
sec_14 <- SLAP_2024_SECCHI.csv%>%
  filter(MULakeNumber == "014")

sec_14_avg <- sec_14 %>%
  group_by(Date)%>%
  summarise(Average_SEC = mean(parameterValue))  #units in m
```

Plot of Secchi Depth
```{r}
sec_14_avg %>%
  ggplot( aes(x=Date, y=Average_SEC))+
  geom_hline(yintercept = 1.11, size = 2, color = "darkorange4")+
  geom_line(aes(group=1), color = "gray76", size = 1.5)+
  geom_point(shape=21, color="black", fill="darkorange4", size=8) +
    theme_bw()+
    theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())+
    xlab('Date')+
    ylab('Depth (m)')+
    labs(title = "Average Secchi Depths for Summer 2024")
```

Chlorophyll A Averages
```{r}
chlA_14 <- SLAP_2024_CHL_A.csv%>%
  filter(MULakeNumber == "014")

chlA_14_avg <- chlA_14 %>%
  group_by(Date)%>%
  summarise(Average_chlA = mean(parameterValue))  #units in ug/L
```

Chlorophyll A Plot
```{r}
chlA_14_avg %>%
  ggplot( aes(x=Date, y=Average_chlA))+
  geom_hline(yintercept = 22.14, size = 2, color = "darkolivegreen")+
  geom_line(aes(group=1), color = "gray76", size = 1.5)+
  geom_point(shape=21, color="black", fill="darkolivegreen", size=8) +
    theme_bw()+
    theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())+
    xlab('Date')+
    ylab('CHL A Concentration (µg/L)')+
    labs(title = "Average Chlorophyll A Concentrations for Summer 2024")
```

## YSI Profiles\

## Temp vs Depth 
```{r}
#after find lake 14, make new column with Fahrenheit instead of Celsius

ysi_14 <- MO_YSIProfileData_2024.csv%>%
  filter(MULakeNumber == "014")

ysi_14te <- ysi_14%>%
  mutate(tempF = (9/5)*temp_degC+32)
```

Temperature vs Depth
```{r}
#treat temp as a function of depth and then reverse later
ggplot(ysi_14te,aes(x=depth_m,y=tempF, group=date))+
  #set up the asthetics, the line must be broken because this is technically discrete data
  geom_line(aes(color =date),size=1.5, linetype=1)+
  #geom_point(aes(color=date))+
  #reverse depth so it starts at zero
  scale_x_reverse()+
  #put the y axis labes on the opposite side so when its flipped it will appear at top
  scale_y_continuous(position="right")+
  #this is how you reverse the look and order or the coordinates for the graph
  coord_flip()+
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())+
  xlab('Depth (m)')+
  ylab('Temperature (°F)')+
  theme(legend.position = "inside", legend.position.inside =  c(.90, .20)) #left to right #up and down

```

DO vs Depth
```{r}
#treat temp as a function of depth and then reverse later
ggplot(ysi_14te,aes(x=depth_m,y=doConcentration_mgpL, group=date))+
  #set up the asthetics, the line must be broken because this is technically discrete data
  geom_line(aes(color =date),size=1.5, linetype=1)+
  #geom_point(aes(color=date))+
  #reverse depth so it starts at zero
  scale_x_reverse()+
  #put the y axis labes on the opposite side so when its flipped it will appear at top
  scale_y_continuous(position="right")+
  #this is how you reverse the look and order or the coordinates for the graph
  coord_flip()+
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())+
  xlab('Depth (m)')+
  ylab('Dissolved Oxygen Concentration (mg/L)')+
  theme(legend.position = "inside", legend.position.inside =  c(.70, .20)) #left to right #up and down
#300 by 450
```