---
title: "Private Lake Reports 2024"
output: html_document
date: "2025-03-17"
---

```{r setup, include=FALSE}
if (!require(dplyr)) {install.packages("dplyr")}
if (!require(tidyverse)) {install.packages("tidyverse")}

library(readr)
library(stringr)
```
## Lakes
14	Tishomingo\
21	Goose Creek\
96	Fellows\
18 & 112	Capri /Shayne\
274	Alpine Lake\
120	Winnebago\
169	Gopher\
411	Cedar Lake (HOA)\
11	Peaceful Valley\
134	Jamesport City Lake\


## Introduction
copy from previous ind lake reports


## Results
1. TN & TP\
add monthly average concentrations for the lake\
add statewide limit for lakes (make a line)

2. Cyanotoxins\
add four toxins in the same graph\
add description of the toxins and what they do (risks)

3. Water Clarity\
graph of chlorophyll A\
not sure we need secchi depth but can add if needed\
make sure the basic understanding is - more chlorophyll means x, and that is why secchi is lower as chlorophyll increases

4. YSI Profiles\
if we include any I think it should be temp and DO to show the thermocline\
maybe possible outcomes of climate change? ex. less turnover -> less DO mixing -> harmful for aquatic life

5. Trophic State\
table with state criteria\
ID lake (oli, meso, eut, hypereut) based on avg summer P. N, Chl, Secchi

## Summary
say if it was average from state or lower or higher. add anything that stood out or to look for going forward. 

## Reference
add references here